// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtobufTest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Person {

  /// <summary>Holder for reflection information generated from ProtobufTest.proto</summary>
  public static partial class ProtobufTestReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtobufTest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtobufTestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJQcm90b2J1ZlRlc3QucHJvdG8SBnBlcnNvbiKkAQoJT25lUGVyc29uEhEK",
            "BG5hbWUYASABKAlIAIgBARIVCghpZE51bWJlchgCIAEoA0gBiAEBEiQKBmdl",
            "bmRlchgDIAEoDjIPLnBlcnNvbi5nZW5kZXJzSAKIAQESFwoKcHJvZmVzc2lv",
            "bhhlIAEoCUgDiAEBQgcKBV9uYW1lQgsKCV9pZE51bWJlckIJCgdfZ2VuZGVy",
            "Qg0KC19wcm9mZXNzaW9uKjQKB2dlbmRlcnMSBwoDbWFuEAASBwoDYm95EAAS",
            "CQoFd29tYW4QARIICgRnaXJsEAEaAhABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Person.genders), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Person.OnePerson), global::Person.OnePerson.Parser, new[]{ "Name", "IdNumber", "Gender", "Profession" }, new[]{ "Name", "IdNumber", "Gender", "Profession" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///枚举类型
  /// </summary>
  public enum genders {
    [pbr::OriginalName("man")] Man = 0,
    [pbr::OriginalName("boy", PreferredAlias = false)] Boy = 0,
    [pbr::OriginalName("woman")] Woman = 1,
    [pbr::OriginalName("girl", PreferredAlias = false)] Girl = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  ///一条message,类似C#中的类
  /// </summary>
  public sealed partial class OnePerson : pb::IMessage<OnePerson>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OnePerson> _parser = new pb::MessageParser<OnePerson>(() => new OnePerson());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OnePerson> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Person.ProtobufTestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnePerson() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnePerson(OnePerson other) : this() {
      _hasBits0 = other._hasBits0;
      name_ = other.name_;
      idNumber_ = other.idNumber_;
      gender_ = other.gender_;
      profession_ = other.profession_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OnePerson Clone() {
      return new OnePerson(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_;
    /// <summary>
    ///[定义声明][数据类型][字段名]=[编号][默认值]
    ///[定义声明]:required:必填字段;optional:可选字段;repeated:可重复字段
    ///[数据类型]:字段的类型,与C#稍有不同,更多类型及其说明请参考官网文档.
    ///[编    号]:唯一标识字段,不可重复,编号1-15使用1个字节进行编码,编号16之后使用两个字节进行编码,推荐将1-15预留给常用的字段,此外编号19000-19999为官方预留,不能使用.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? ""; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "idNumber" field.</summary>
    public const int IdNumberFieldNumber = 2;
    private long idNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long IdNumber {
      get { if ((_hasBits0 & 1) != 0) { return idNumber_; } else { return 0L; } }
      set {
        _hasBits0 |= 1;
        idNumber_ = value;
      }
    }
    /// <summary>Gets whether the "idNumber" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIdNumber {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "idNumber" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIdNumber() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 3;
    private global::Person.genders gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Person.genders Gender {
      get { if ((_hasBits0 & 2) != 0) { return gender_; } else { return global::Person.genders.Man; } }
      set {
        _hasBits0 |= 2;
        gender_ = value;
      }
    }
    /// <summary>Gets whether the "gender" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGender {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "gender" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGender() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "profession" field.</summary>
    public const int ProfessionFieldNumber = 101;
    private string profession_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Profession {
      get { return profession_ ?? ""; }
      set {
        profession_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "profession" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasProfession {
      get { return profession_ != null; }
    }
    /// <summary>Clears the value of the "profession" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearProfession() {
      profession_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OnePerson);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OnePerson other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (IdNumber != other.IdNumber) return false;
      if (Gender != other.Gender) return false;
      if (Profession != other.Profession) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasIdNumber) hash ^= IdNumber.GetHashCode();
      if (HasGender) hash ^= Gender.GetHashCode();
      if (HasProfession) hash ^= Profession.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasIdNumber) {
        output.WriteRawTag(16);
        output.WriteInt64(IdNumber);
      }
      if (HasGender) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Gender);
      }
      if (HasProfession) {
        output.WriteRawTag(170, 6);
        output.WriteString(Profession);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasIdNumber) {
        output.WriteRawTag(16);
        output.WriteInt64(IdNumber);
      }
      if (HasGender) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Gender);
      }
      if (HasProfession) {
        output.WriteRawTag(170, 6);
        output.WriteString(Profession);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasIdNumber) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdNumber);
      }
      if (HasGender) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (HasProfession) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Profession);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OnePerson other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasIdNumber) {
        IdNumber = other.IdNumber;
      }
      if (other.HasGender) {
        Gender = other.Gender;
      }
      if (other.HasProfession) {
        Profession = other.Profession;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            IdNumber = input.ReadInt64();
            break;
          }
          case 24: {
            Gender = (global::Person.genders) input.ReadEnum();
            break;
          }
          case 810: {
            Profession = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            IdNumber = input.ReadInt64();
            break;
          }
          case 24: {
            Gender = (global::Person.genders) input.ReadEnum();
            break;
          }
          case 810: {
            Profession = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
